In [1]:
import pandas as pd

In [3]:
dataframe = pd.read_csv("iris.csv", sep=";")
dataframe

    sepal_length,sepal_width,petal_length,petal_width,species
0                                   5.1,3.5,1.4,0.2,se
1                                 4.9,3,1.4,0.2,setosa
2                               4.7,3.2,1.3,0.2,setosa
3                               4.6,3.1,1.5,0.2,setosa
4                                 5,3.6,1.4,0.2,setosa
..                                                 ...
145                            6.7,3,5.2,2.3,virginica
146                            6.3,2.5,5,1.9,virginica
147                              6.5,3,5.2,2,virginica
148                          6.2,3.4,5.4,2.3,virginica
149                            5.9,3,5.1,1.8,virginica

[150 rows x 1 columns]